name: CI/CD Pipeline

on:
  push:
    branches:
      - main   # run pipeline when code is pushed to main
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Install dependencies & run tests for backend
      - name: Install backend dependencies
        run: |
          cd backend
          npm install
          npm run lint
          npm test

      # Install dependencies & run build for frontend
      - name: Install frontend dependencies
        run: |
          cd frontend
          npm install
          npm run lint
          npm run build

      # Upload frontend build artifacts
      - name: Upload production-ready build
        uses: actions/upload-artifact@v3
        with:
          name: frontend-build
          path: frontend/build
